#!/usr/bin/env sh
# Layout System
yabai -m config layout                        bsp
yabai -m config mouse_follows_focus           on
yabai -m config focus_follows_mouse           off
yabai -m config window_topmost                on
yabai -m config auto_balance                  on

# Variables
CENTERED_GRID=4:4:1:1:2:2

# Window Padding
SPACEBAR_HEIGHT=$(sketchybar -m --query bar  | jq '.height')
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# Applications
yabai -m rule --add app="^System Settings$" manage=off grid=$CENTERED_GRID
yabai -m rule --add app="^App Store$" manage=off grid=$CENTERED_GRID

# Delete Screens
# yabai -m signal --add event=space_changed action="sh /Users/magtastic/.config/yabai/destory_empty_spaces.sh"

# Sketchybar events
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
